### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [jupdike/t-s-eliot_poems#1]
- Long description must be escaped HTML outside of the CDATA tag.  Within CDATA you write raw HTML, then `clean` will remove the CDATA tag and escape the HTML for you.  See other content.opf files for an example.
- Hathi Trust links must be to the book's catalog record, not the page scans themselves

**Comment by jupdike** [comment]
"Within CDATA you write raw HTML, then clean will remove the CDATA tag and escape the HTML for you."

This would be a useful bit of info on the Step-by-Step page, step 17.

Fixed.

**Comment by acabal** [comment]
A metadata manual is on my very long to-do list :)
