### ISSUE TITLE
Semantics/styling

### ISSUE THREAD

**Issue by acabal** [jupdike/t-s-eliot_poems#4]
- Remove `chapter` semantic from poems, not necessary here (they're not chapters)
- Remove classes that are aliases for presentation styles where possible, for example `class="smallcaps"`.  We must name classes after what they are styling, not what style they create.  A better approach would be to use an unsemantic `<b>` tag and style that to no-bold small-caps in `local.css`.
- For stanzas that contain `span.right`, we have to give the `<p>` tag `display: inline-block`, otherwise the span will be way too far right aligned in wide displays.  We could give the `<p>` tag `class="right"` also, and then style the class to target `p.right{ display: inline-block; } ` and `span.right{ text-align: right}` respectively.
- IDs in subsections should not have roman numerals (for example `id="the-waste-land-iv"` should be `id="the-waste-land-4"`
- We can improve the ID pattern for forward references.  Instead of for example `id="forward-ref-44"` pattern, why not `id="the-waste-land-line-376"`? 

Make sure to do `git pull` on the tools and run lint again which will catch some more minor stuff for you.

**Comment by jupdike** [comment]
OK I did all that stuff and fixed the things that lint unveiled.
