### ISSUE TITLE
ToC/Colophon issues

### ISSUE THREAD

**Issue by acabal** [jupdike/t-s-eliot_poems#5]
- Endnotes must be in ToC landmarks
- Change "was published 1915⁠–⁠1922 by" to "is compiled from poems published from 1915⁠–⁠1922 by"

**Comment by acabal** [comment]
- For transcription dates we just use the earliest date in the PG metadata, so remove the time spans there

**Comment by acabal** [comment]
- For Hathi Trust link, for now just make it a single link going to the first Hathi source.  We don't yet have a pattern for dealing with multiple scans from the same source, we can always sort that out later.  Make sure the imprint also matches how the colophon source is structured

**Comment by jupdike** [comment]
What about the two PG links? do the same? (i.e. use just PG Poems link, not The Waste Land on the imprint?)

**Comment by acabal** [comment]
Yes, for now.  There is no standard for this yet so let's keep the style the rest of the ebooks are using, but I'm open to suggestions on the mailing list.
